---
- name: Deploy Java Web Application
  hosts: group1
  become: true

  tasks:
    - name: Copy WAR file to the deployment directory
      copy:
        src: "{{ war_file }}"
        dest: "/path/to/deployment/directory/your_app.war"
      notify:
        - Restart Tomcat

  handlers:
    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
      when: ansible_os_family == 'RedHat'

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
      when: ansible_distribution == 'Ubuntu'

    - name: Restart Tomcat
      service:
        name: tomcat
        state: restarted
      when: ansible_distribution == 'Amazon'
...
