---
- name: Deploy WAR file to Tomcat
  hosts: group1
  become: yes

  vars:
    tomcat_version: "apache-tomcat-10.1.16"
    tomcat_home: "/usr/local/bin/{{ tomcat_version }}"
    webapps_dir: "{{ tomcat_home }}/webapps"

  tasks:
    - name: Remove existing WAR files
      file:
        path: "{{ webapps_dir }}/*.war"
        state: absent
      ignore_errors: yes

    - name: Move new WAR files to Tomcat webapps directory
      command: mv "{{ item }}" "{{ webapps_dir }}/"
      with_fileglob: /usr/local/bin/*.war

    - name: Set execute permissions for Tomcat scripts
      ansible.builtin.file:
        path: "{{ tomcat_home }}/bin/*.sh"
        mode: 'u+x,g+x'
        recurse: yes

    - name: System CTL - Daemon reload
      ansible.builtin.command: "systemctl daemon-reload"
      when: "'Amazon' in ansible_distribution or 'CentOS' in ansible_distribution or 'Ubuntu' in ansible_distribution"

    - name: Restart Tomcat
      ansible.builtin.systemd:
        name: "{{ tomcat_version }}"
        state: restarted
...
