---
- name: Deploy WAR file to Tomcat
  hosts: group1
  gather_facts: true
  become: yes

  vars:
    workspace: "{{ workspace | default('/home/centos/workspace/ansibleproject') }}"
    tomcat_home: "/usr/local/bin/apache-tomcat-10.1.16"
    tomcat_service: "tomcat"

  tasks:
    - name: Check if Tomcat is installed
      stat:
        path: "{{ tomcat_home }}"
      register: tomcat_installed

    - name: Fetch the latest WAR file
      ansible.builtin.find:
        paths: "{{ workspace }}"
        patterns: "*.war"
      register: latest_war
      when: tomcat_installed.stat.exists

    - name: Stop Tomcat
      ansible.builtin.service:
        name: "{{ tomcat_service }}"
        state: stopped
      when: tomcat_installed.stat.exists

    - name: Remove existing WAR file from Tomcat webapps directory
      ansible.builtin.find:
        paths: "{{ tomcat_home }}/webapps/"
        patterns: "*.war"
        recurse: yes
      register: old_war_files
      when: tomcat_installed.stat.exists

    - name: Copy the latest WAR file to the target directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ tomcat_home }}/webapps/"
      with_items: "{{ latest_war.files }}"
      when: latest_war.matched > 0

    - name: Reload Tomcat
      ansible.builtin.service:
        name: "{{ tomcat_service }}"
        state: reloaded
      when: tomcat_installed.stat.exists

    - name: Start Tomcat
      ansible.builtin.service:
        name: "{{ tomcat_service }}"
        state: started
      when: tomcat_installed.stat.exists
...
