---
- name: Deploy WAR file to Tomcat
  hosts: group1
  gather_facts: true
  become: yes

  vars:
    workspace: "{{ workspace | default('/home/centos/workspace/ansibleproject') }}"
    tomcat_home: "/usr/local/bin/apache-tomcat-10.1.16"

  tasks:
    - name: Fetch the latest WAR file
      ansible.builtin.find:
        paths: "{{ workspace }}"
        patterns: "*.war"
      register: latest_war

    - name: Check if Tomcat is running
      ansible.builtin.shell:
        cmd: "{{ tomcat_home }}/bin/version.sh"
      register: tomcat_version
      ignore_errors: true

    - name: Stop Tomcat if running
      ansible.builtin.shell:
        cmd: "{{ tomcat_home }}/bin/shutdown.sh"
      when: tomcat_version.rc == 0 and latest_war.matched > 0

    - name: Remove existing WAR file from Tomcat webapps directory
      ansible.builtin.find:
        paths: "{{ tomcat_home }}/webapps/"
        patterns: "*.war"
        recurse: yes
      register: old_war_files
      when: tomcat_version.rc == 0 and latest_war.matched > 0

    - name: Copy the latest WAR file to the target directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ tomcat_home }}/webapps/"
      with_items: "{{ latest_war.files }}"
      when: tomcat_version.rc == 0 and latest_war.matched > 0

    - name: Start Tomcat
      ansible.builtin.shell:
        cmd: "{{ tomcat_home }}/bin/startup.sh"
      when: tomcat_version.rc == 0 and latest_war.matched > 0
...
