---
- name: Deploy WAR file to Tomcat
  hosts: group1
  become: yes

  tasks:
    - name: Ensure the target directory exists
      file:
        path: "~/apache*/webapps/"
        state: directory

    - name: Copy WAR file to Tomcat webapps directory
      ansible.builtin.find:
        paths: "{{ workspace }}/target/"
        patterns: "*.war"
      register: war_files

    - name: Check if WAR file exists
      fail:
        msg: "No WAR file found in {{ workspace }}/target/"
      when: war_files.matched == 0

    - name: Copy WAR file(s) to Tomcat
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "~/apache*/webapps/"
      with_items: "{{ war_files.files }}"
...
