---
- name: Deploy WAR file to Tomcat
  hosts: your_tomcat_hosts
  gather_facts: true
  become: yes

  tasks:
    - name: Check if Tomcat is installed
      stat:
        path: "/usr/local/apache-tomcat-10.1.16"
      register: tomcat_installed
    
    - name: Stop Tomcat
      systemd:
        name: tomcat
        state: stopped
      when: tomcat_installed.stat.exists
      
    - name: Remove existing WAR file from Tomcat webapps directory
      ansible.builtin.find:
        paths: "/usr/local/apache-tomcat-10.1.16/webapps/"
        patterns: "*.war"
        recurse: yes
      register: old_war_files
      when: tomcat_installed.stat.exists and 
            (ansible_distribution == "Ubuntu" or ansible_distribution == "CentOS" or ansible_distribution == "Amazon")

    - name: Copy the latest WAR file to the target directory
      ansible.builtin.copy:
        src: "{{ latest_war.stdout }}"
        dest: "/usr/local/apache-tomcat-10.1.16/webapps/"

    - name: Reload Tomcat
      ansible.builtin.service:
        name: "{{ tomcat_service }}"
        state: reloaded

    - name: Start Tomcat
      ansible.builtin.service:
        name: "{{ tomcat_service }}"
        state: started
...
