---
- name: Deploy Java Web Application
  hosts: group1
  become: true

  vars:
    tomcat_user: "{{ ansible_user }}"  # Set this to the user running the Tomcat process

  tasks:
    - name: Remove existing WAR files from Tomcat webapps directory
      ansible.builtin.shell:
        cmd: "sudo rm -rf /usr/local/latest/webapps/*.war"
      become_user: "{{ tomcat_user }}"
      become_method: sudo
      when: ansible_os_family == 'RedHat'

    - name: Remove existing WAR files from Tomcat webapps directory
      ansible.builtin.shell:
        cmd: "sudo rm -rf /usr/local/latest/webapps/*.war"
      become_user: "{{ tomcat_user }}"
      become_method: sudo
      when: ansible_os_family == 'Debian'

    - name: Copy WAR file to Tomcat webapps directory
      ansible.builtin.shell:
        cmd: "sudo mv {{ war_file }} /usr/local/latest/webapps/"
      become_user: "{{ tomcat_user }}"
      become_method: sudo
      when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

    - name: Reload systemd configuration
      ansible.builtin.systemd:
        daemon_reload: yes
      become_user: "{{ tomcat_user }}"
      become_method: sudo
      when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

    - name: Start Tomcat
      ansible.builtin.shell:
        cmd: "/usr/local/latest/bin/startup.sh"
      become_user: "{{ tomcat_user }}"
      become_method: sudo
      when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'
...
