---
- name: Deploy Java Web Application
  hosts: "{{ target_node }}"
  become: yes

  vars:
    webapp_source_path: "/home/centos/workspace/ansibleproject/target/path/on/ansible/master/application.war"
    webapp_dest_path: "/path/on/target/server/application.war"
    tomcat_service_name: "tomcat"  # Adjust with your actual Tomcat service name

  tasks:
    - name: Copy WAR file to Tomcat webapps directory
      ansible.builtin.copy:
        src: "{{ webapp_source_path }}"
        dest: "{{ webapp_dest_path }}"
      notify:
        - Restart Tomcat

  handlers:
    - name: Restart Tomcat
      ansible.builtin.service:
        name: "{{ tomcat_service_name }}"
        state: restarted
...
