---
- name: Deploy WAR file to Tomcat
  hosts: your_tomcat_hosts
  gather_facts: true

  tasks:
    - name: Find the latest WAR file in the target directory
      ansible.builtin.shell:
        cmd: "ls -t {{ workspace }}/target/*.war | head -n1"
      register: latest_war

    - name: Copy the latest WAR file to the target directory
      ansible.builtin.copy:
        src: "{{ latest_war.stdout }}"
        dest: "~/apache*/webapps/"

    - name: Remove old WAR files from Tomcat webapps directory
      ansible.builtin.find:
        paths: "~/apache*/webapps/"
        patterns: "*.war"
        recurse: yes
      register: old_war_files

    - name: Remove old WAR files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ old_war_files.files }}"

    - name: Reload Tomcat
      ansible.builtin.service:
        name: "{{ tomcat_service }}"
        state: reloaded

    - name: Start Tomcat
      ansible.builtin.service:
        name: "{{ tomcat_service }}"
        state: started
...
