---
- name: Deploy Web App on Tomcat
  hosts: group1
  become: true

  tasks:
    - name: Copy WAR file to Tomcat webapps directory
      copy:
        src: "{{ workspace }}/your_webapp.war"
        dest: "{{ tomcat_webapps_path }}"
        mode: 0644
      notify:
        - Restart Tomcat

    - name: Enable and start Tomcat service
      service:
        name: "{{ tomcat_service_name }}"
        enabled: yes
        state: started

  handlers:
    - name: Restart Tomcat
      service:
        name: "{{ tomcat_service_name }}"
        state: restarted

  vars:
    tomcat_webapps_path: "/usr/share/tomcat/webapps"  # Default path for most distributions
    tomcat_service_name: "tomcat"                    # Default service name for most distributions
...
