---
- name: Deploy webapp on tomcat
  hosts: group1
  become: yes  # Run tasks with sudo
  tasks:
    - name: Check OS distribution
      ansible.builtin.set_fact:
        os_distribution: "{{ ansible_distribution | lower }}"

    - name: Stop Tomcat
      ansible.builtin.shell:
        cmd: "pkill -f catalina"  # Adjust the command based on how Tomcat is started on your nodes
      ignore_errors: yes

    - name: Delete existing .war files in Tomcat webapps folder
      ansible.builtin.file:
        path: "/usr/local/bin/apache-tomcat-10.1.16/webapps/*war"
        state: absent
      when: os_distribution in ['centos', 'ubuntu', 'amazon']

    - name: Copy .war files to Tomcat webapps folder
      ansible.builtin.copy:
        src: "/home/centos/workspace/ansibleproject/target/*war"
        dest: "/usr/local/bin/apache-tomcat-10.1.16/webapps/"
        mode: '0644'
      when: os_distribution in ['centos', 'ubuntu', 'amazon']

    - name: Starting Tomcat
      ansible.builtin.shell:
        cmd: "nohup /usr/local/bin/apache-tomcat-10.1.16/bin/startup.sh >> /path/to/tomcat.log 2>&1 &"
      when: os_distribution in ['centos', 'ubuntu', 'amazon']
...
