---
- name: Deploy webapp on Tomcat
  hosts: group1
  become: yes
  tasks:
    - name: Check OS distribution
      ansible.builtin.set_fact:
        os_distribution: "{{ ansible_distribution | lower }}"

    - name: Stop Tomcat
      ansible.builtin.shell:
        cmd: "pkill -f catalina"
      ignore_errors: yes
      when: os_distribution in ['centos', 'ubuntu', 'amazon']

    - name: Delete existing .war files in Tomcat webapps folder
      ansible.builtin.file:
        path: "/usr/local/bin/apache-tomcat-10.1.16/webapps/*war"
        state: absent
      when: os_distribution in ['centos', 'ubuntu', 'amazon']

    - name: Ensure webapps directory exists
      ansible.builtin.file:
        path: "/usr/local/bin/apache-tomcat-10.1.16/webapps/"
        state: directory
      when: os_distribution in ['centos', 'ubuntu', 'amazon']

    - name: Debug - List files in source directory
      ansible.builtin.find:
        paths: "/home/centos/workspace/ansibleproject/target/"
        recurse: yes
      when: os_distribution in ['centos', 'ubuntu', 'amazon']

    - name: Debug - List files in Tomcat webapps folder
      ansible.builtin.shell:
        cmd: "ls -l /usr/local/bin/apache-tomcat-10.1.16/webapps/"
      when: os_distribution in ['centos', 'ubuntu', 'amazon']

    - name: Copy .war files to Tomcat webapps folder
      ansible.builtin.shell:
        cmd: "rsync -av --include='*.war' --exclude='*' /home/centos/workspace/ansibleproject/target/ /usr/local/bin/apache-tomcat-10.1.16/webapps/"
      when: os_distribution in ['centos', 'ubuntu', 'amazon']
      register: rsync_result

    - debug:
        var: rsync_result

    - name: Starting Tomcat
      ansible.builtin.shell:
        cmd: "nohup /usr/local/bin/apache-tomcat-10.1.16/bin/startup.sh >> /path/to/tomcat.log 2>&1 &"
      when: os_distribution in ['centos', 'ubuntu', 'amazon']
...
