---
- name: Deploy Java Web Application
  hosts: group1
  become: true

  tasks:
    - name: Set Tomcat paths based on distribution
      ansible.builtin.command:
        cmd: mv "/usr/local/apache-tomcat-10.1.16" "/usr/local/latest"
      when: "'/usr/local/latest' is not exists"
      delegate_to: "{{ inventory_hostname }}"

    - name: Copy WAR file to Tomcat webapps directory
      ansible.builtin.copy:
        src: "{{ ansible_env.WORKSPACE }}/target/*.war"
        dest: "/usr/local/latest/webapps/"
        remote_src: true
      become_user: "{{ ansible_user }}"
      delegate_to: "{{ inventory_hostname }}"
...
