---
- name: Deploy WAR file to Tomcat
  hosts: group1
  become: yes

  vars:
    tomcat_service: "{{ 'tomcat8' if ansible_distribution == 'Ubuntu' else 'tomcat' }}"

  tasks:
    - name: Ensure the target directory exists
      ansible.builtin.file:
        path: "~/apache*/webapps/"
        state: directory

    - name: Stash the new WAR file
      ansible.builtin.stash:
        name: new_war
        include:
          - "{{ workspace }}/target/*.war"

    - name: Remove old WAR files from Tomcat webapps directory
      ansible.builtin.find:
        paths: "~/apache*/webapps/"
        patterns: "*.war"
        recurse: yes
      register: old_war_files

    - name: Remove old WAR files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ old_war_files.files }}"

    - name: Unstash the new WAR file
      ansible.builtin.unarchive:
        src: "{{ item }}"
        dest: "~/apache*/webapps/"
      with_items: "{{ stashes.new_war }}"

    - name: Reload Tomcat
      ansible.builtin.service:
        name: "{{ tomcat_service }}"
        state: reloaded

    - name: Start Tomcat
      ansible.builtin.service:
        name: "{{ tomcat_service }}"
        state: started
...
