---
- name: Deploy Java Web Application
  hosts: group1
  become: yes
  tasks:
    - name: Remove existing WAR files from Tomcat webapps directory
      shell: rm -rf ~/apache*/webapps/*.war
      when: ansible_os_family in ['RedHat', 'Debian']

    - name: Copy WAR file to Tomcat webapps directory
      shell: mv {{ war_file }} ~/apache*/webapps/
      when: ansible_os_family in ['RedHat', 'Debian']

    - name: Reload systemd (if needed)
      systemd:
        name: tomcat
        state: restarted
      when: ansible_os_family in ['RedHat']

    - name: Start Tomcat
      shell: ~/apache-tomcat-7.0.94/bin/startup.sh
      when: ansible_os_family in ['RedHat', 'Debian']
...
