---
- name: Deploy Web App on Tomcat
  hosts: group1
  become: true

  tasks:
    - name: Copy WAR file to Tomcat webapps directory
      ansible.builtin.copy:
        src: "{{ WORKSPACE_PATH }}/path/on/ansible/master/application.war"
        dest: "/path/on/target/server/application.war"
      notify:
        - Restart Tomcat

    - name: Enable and start Tomcat service
      service:
        name: "{{ tomcat_service_name }}"
        enabled: yes
        state: started

  handlers:
    - name: Restart Tomcat
      ansible.builtin.service:
        name: "{{ tomcat_service_name }}"
        state: restarted

  vars:
    tomcat_webapps_path: "/usr/share/tomcat/webapps"  # Default path for most distributions
    tomcat_service_name: "tomcat"                    # Default service name for most distributions
...
