---
- name: Deploy Java Web Application
  hosts: group1
  become: yes

  tasks:
    - name: Set Tomcat paths based on distribution
      set_fact:
        tomcat_path: >-
          {% if ansible_distribution == 'CentOS' %}
            /usr/local/apache-tomcat-10.1.16
          {% elif ansible_distribution == 'Ubuntu' %}
            /usr/local/apache-tomcat-10.1.16
          {% elif ansible_distribution == 'Amazon' %}
            /path/to/amazon/tomcat
          {% else %}
            /default/tomcat/path
          {% endif %}

    - name: Copy WAR file to Tomcat webapps directory
      ansible.builtin.copy:
        src: "{{ workspace_path }}/target/*.war"
        dest: "{{ tomcat_path }}/webapps/"
      notify:
        - Restart Tomcat

  handlers:
    - name: Restart Tomcat
      ansible.builtin.service:
        name: "tomcat"  # Adjust with your actual Tomcat service name
        state: restarted
...
